### ISSUE TITLE
Rows should be collapsed directly when clicking on the arrow.

### ISSUE THREAD

**Issue by designbywilliam** [anomalylabs/repeater-field_type#1]
The ui would benefit if the row closed directly when you click on the down arrow instead of opening a dropdown.

Instead, the dropdown could be opened when clicking the cogwheel, if more settings are necessary.

Might also benefit from a X (delete) icon which deletes the row.

A little bit torn if we need a confirmation message on delete or not. Im 50/50 if its helpful or annoying.

**Comment by RyanThompson** [comment]
I am going to add a double click on the bar to toggle collapse. I think that will work better.

I had 2 icons - one collapse and one trash but they were too close and too far when opposite of each other. Collapse is necessary cause options will grow a bit. Dbl click for the quick collapse. Boom.

Thoughts?

**Comment by designbywilliam** [comment]
Yes, collapse is a must for sure! 

Double click or single click. I personally think i would prefer a single click. It should be faster. Esp if you need to close many.

The icon placement issue thing would be css/html right?

**Comment by RyanThompson** [comment]
No the icon placement was an issue with visual weight and placement of actionable items. Too close and they slop together / cause accidents - too far apart and the experience is disjointed. 

Single clicks will get lost with dragging accidents. Double clicks are pretty commonplace for meta actions I think (people click the fuck out of things that are actionable so 2+ clicks lol)

**Comment by designbywilliam** [comment]
I guess my finger isn't fast as it used to be ;)

**Comment by RyanThompson** [comment]
Needs more practice.

**Comment by RyanThompson** [comment]
UI changes coming up - closing this for meow
