### ISSUE TITLE
Nested Repeater fields return white page or break the form page after save

### ISSUE THREAD

**Issue by fryiee** [anomalylabs/repeater-field_type#8]
As title. If I create a new record with nested repeater fields, on save I'm returned a white screen. If I go back and view, the record is saved but none of the repeaters are (parent or child).

If I create a new record with just the top level repeater field, it saves as in intended. If I then go back and add a new row to the repeater and save, it breaks the form page from then on:
![image](https://cloud.githubusercontent.com/assets/5254791/24230653/4a6e589a-0fd4-11e7-915c-c85a6bd9c699.png)

**Comment by RyanThompson** [comment]
Wrong repo
